// Copyright Jetstack Ltd. See LICENSE for details.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type MachineExpansion interface{}

type MachineDeploymentExpansion interface{}

type MachineSetExpansion interface{}
