/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by apiregister-gen. Do not edit it manually!

package v1alpha1

import (
	"github.com/jetstack/wing-api/pkg/apis/wing"
	"github.com/kubernetes-incubator/apiserver-builder/pkg/builders"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

var (
	wingMachineStorage = builders.NewApiResource( // Resource status endpoint
		wing.InternalMachine,
		MachineSchemeFns{},
		func() runtime.Object { return &Machine{} },     // Register versioned resource
		func() runtime.Object { return &MachineList{} }, // Register versioned resource list
		&MachineStrategy{builders.StorageStrategySingleton},
	)
	wingMachineSetStorage = builders.NewApiResource( // Resource status endpoint
		wing.InternalMachineSet,
		MachineSetSchemeFns{},
		func() runtime.Object { return &MachineSet{} },     // Register versioned resource
		func() runtime.Object { return &MachineSetList{} }, // Register versioned resource list
		&MachineSetSrategy{builders.StorageStrategySingleton},
	)
	ApiVersion = builders.NewApiVersion("wing.tarmak.io", "v1alpha1").WithResources(
		wingMachineStorage,
		builders.NewApiResource( // Resource status endpoint
			wing.InternalMachineStatus,
			MachineSchemeFns{},
			func() runtime.Object { return &Machine{} },     // Register versioned resource
			func() runtime.Object { return &MachineList{} }, // Register versioned resource list
			&MachineStatusStrategy{builders.StatusStorageStrategySingleton},
		), wingMachineSetStorage,
		builders.NewApiResource( // Resource status endpoint
			wing.InternalMachineSetStatus,
			MachineSetSchemeFns{},
			func() runtime.Object { return &MachineSet{} },     // Register versioned resource
			func() runtime.Object { return &MachineSetList{} }, // Register versioned resource list
			&MachineSetSrategyStatusStrategy{builders.StatusStorageStrategySingleton},
		))

	// Required by code generated by go2idl
	AddToScheme        = ApiVersion.SchemaBuilder.AddToScheme
	SchemeBuilder      = ApiVersion.SchemaBuilder
	localSchemeBuilder = &SchemeBuilder
	SchemeGroupVersion = ApiVersion.GroupVersion
)

// Required by code generated by go2idl
// Kind takes an unqualified kind and returns a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Required by code generated by go2idl
// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

//
// Machine Functions and Structs
//
// +k8s:deepcopy-gen=false
type MachineSchemeFns struct {
	builders.DefaultSchemeFns
}

// +k8s:deepcopy-gen=false
type MachineStrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type MachineStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type MachineList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Machine `json:"items"`
}

//
// MachineSet Functions and Structs
//
// +k8s:deepcopy-gen=false
type MachineSetSchemeFns struct {
	builders.DefaultSchemeFns
}

// +k8s:deepcopy-gen=false
type MachineSetSrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type MachineSetSrategyStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type MachineSetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MachineSet `json:"items"`
}
