// +build !ignore_autogenerated

// Copyright Jetstack Ltd. See LICENSE for details.

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	wing "github.com/jetstack/wing-api/pkg/apis/wing"
	common "github.com/jetstack/wing-api/pkg/apis/wing/common"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Machine)(nil), (*wing.Machine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Machine_To_wing_Machine(a.(*Machine), b.(*wing.Machine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*wing.Machine)(nil), (*Machine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_wing_Machine_To_v1alpha1_Machine(a.(*wing.Machine), b.(*Machine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineList)(nil), (*wing.MachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineList_To_wing_MachineList(a.(*MachineList), b.(*wing.MachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*wing.MachineList)(nil), (*MachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_wing_MachineList_To_v1alpha1_MachineList(a.(*wing.MachineList), b.(*MachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineSet)(nil), (*wing.MachineSet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineSet_To_wing_MachineSet(a.(*MachineSet), b.(*wing.MachineSet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*wing.MachineSet)(nil), (*MachineSet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_wing_MachineSet_To_v1alpha1_MachineSet(a.(*wing.MachineSet), b.(*MachineSet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineSetList)(nil), (*wing.MachineSetList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineSetList_To_wing_MachineSetList(a.(*MachineSetList), b.(*wing.MachineSetList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*wing.MachineSetList)(nil), (*MachineSetList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_wing_MachineSetList_To_v1alpha1_MachineSetList(a.(*wing.MachineSetList), b.(*MachineSetList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineSetSpec)(nil), (*wing.MachineSetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineSetSpec_To_wing_MachineSetSpec(a.(*MachineSetSpec), b.(*wing.MachineSetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*wing.MachineSetSpec)(nil), (*MachineSetSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_wing_MachineSetSpec_To_v1alpha1_MachineSetSpec(a.(*wing.MachineSetSpec), b.(*MachineSetSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineSetSrategy)(nil), (*wing.MachineSetSrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineSetSrategy_To_wing_MachineSetSrategy(a.(*MachineSetSrategy), b.(*wing.MachineSetSrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*wing.MachineSetSrategy)(nil), (*MachineSetSrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_wing_MachineSetSrategy_To_v1alpha1_MachineSetSrategy(a.(*wing.MachineSetSrategy), b.(*MachineSetSrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineSetSrategyStatusStrategy)(nil), (*wing.MachineSetSrategyStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineSetSrategyStatusStrategy_To_wing_MachineSetSrategyStatusStrategy(a.(*MachineSetSrategyStatusStrategy), b.(*wing.MachineSetSrategyStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*wing.MachineSetSrategyStatusStrategy)(nil), (*MachineSetSrategyStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_wing_MachineSetSrategyStatusStrategy_To_v1alpha1_MachineSetSrategyStatusStrategy(a.(*wing.MachineSetSrategyStatusStrategy), b.(*MachineSetSrategyStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineSetStatus)(nil), (*wing.MachineSetStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineSetStatus_To_wing_MachineSetStatus(a.(*MachineSetStatus), b.(*wing.MachineSetStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*wing.MachineSetStatus)(nil), (*MachineSetStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_wing_MachineSetStatus_To_v1alpha1_MachineSetStatus(a.(*wing.MachineSetStatus), b.(*MachineSetStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineSpec)(nil), (*wing.MachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineSpec_To_wing_MachineSpec(a.(*MachineSpec), b.(*wing.MachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*wing.MachineSpec)(nil), (*MachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_wing_MachineSpec_To_v1alpha1_MachineSpec(a.(*wing.MachineSpec), b.(*MachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineSpecManifest)(nil), (*wing.MachineSpecManifest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineSpecManifest_To_wing_MachineSpecManifest(a.(*MachineSpecManifest), b.(*wing.MachineSpecManifest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*wing.MachineSpecManifest)(nil), (*MachineSpecManifest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_wing_MachineSpecManifest_To_v1alpha1_MachineSpecManifest(a.(*wing.MachineSpecManifest), b.(*MachineSpecManifest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineStatus)(nil), (*wing.MachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineStatus_To_wing_MachineStatus(a.(*MachineStatus), b.(*wing.MachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*wing.MachineStatus)(nil), (*MachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_wing_MachineStatus_To_v1alpha1_MachineStatus(a.(*wing.MachineStatus), b.(*MachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineStatusManifest)(nil), (*wing.MachineStatusManifest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineStatusManifest_To_wing_MachineStatusManifest(a.(*MachineStatusManifest), b.(*wing.MachineStatusManifest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*wing.MachineStatusManifest)(nil), (*MachineStatusManifest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_wing_MachineStatusManifest_To_v1alpha1_MachineStatusManifest(a.(*wing.MachineStatusManifest), b.(*MachineStatusManifest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineStatusStrategy)(nil), (*wing.MachineStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineStatusStrategy_To_wing_MachineStatusStrategy(a.(*MachineStatusStrategy), b.(*wing.MachineStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*wing.MachineStatusStrategy)(nil), (*MachineStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_wing_MachineStatusStrategy_To_v1alpha1_MachineStatusStrategy(a.(*wing.MachineStatusStrategy), b.(*MachineStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineStrategy)(nil), (*wing.MachineStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineStrategy_To_wing_MachineStrategy(a.(*MachineStrategy), b.(*wing.MachineStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*wing.MachineStrategy)(nil), (*MachineStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_wing_MachineStrategy_To_v1alpha1_MachineStrategy(a.(*wing.MachineStrategy), b.(*MachineStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineTemplateSpec)(nil), (*wing.MachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineTemplateSpec_To_wing_MachineTemplateSpec(a.(*MachineTemplateSpec), b.(*wing.MachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*wing.MachineTemplateSpec)(nil), (*MachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_wing_MachineTemplateSpec_To_v1alpha1_MachineTemplateSpec(a.(*wing.MachineTemplateSpec), b.(*MachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Machine_To_wing_Machine(in *Machine, out *wing.Machine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_MachineSpec_To_wing_MachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_MachineStatus_To_wing_MachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Machine_To_wing_Machine is an autogenerated conversion function.
func Convert_v1alpha1_Machine_To_wing_Machine(in *Machine, out *wing.Machine, s conversion.Scope) error {
	return autoConvert_v1alpha1_Machine_To_wing_Machine(in, out, s)
}

func autoConvert_wing_Machine_To_v1alpha1_Machine(in *wing.Machine, out *Machine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_wing_MachineSpec_To_v1alpha1_MachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_wing_MachineStatus_To_v1alpha1_MachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_wing_Machine_To_v1alpha1_Machine is an autogenerated conversion function.
func Convert_wing_Machine_To_v1alpha1_Machine(in *wing.Machine, out *Machine, s conversion.Scope) error {
	return autoConvert_wing_Machine_To_v1alpha1_Machine(in, out, s)
}

func autoConvert_v1alpha1_MachineList_To_wing_MachineList(in *MachineList, out *wing.MachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]wing.Machine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_MachineList_To_wing_MachineList is an autogenerated conversion function.
func Convert_v1alpha1_MachineList_To_wing_MachineList(in *MachineList, out *wing.MachineList, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineList_To_wing_MachineList(in, out, s)
}

func autoConvert_wing_MachineList_To_v1alpha1_MachineList(in *wing.MachineList, out *MachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Machine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_wing_MachineList_To_v1alpha1_MachineList is an autogenerated conversion function.
func Convert_wing_MachineList_To_v1alpha1_MachineList(in *wing.MachineList, out *MachineList, s conversion.Scope) error {
	return autoConvert_wing_MachineList_To_v1alpha1_MachineList(in, out, s)
}

func autoConvert_v1alpha1_MachineSet_To_wing_MachineSet(in *MachineSet, out *wing.MachineSet, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_MachineSetSpec_To_wing_MachineSetSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_MachineSetStatus_To_wing_MachineSetStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_MachineSet_To_wing_MachineSet is an autogenerated conversion function.
func Convert_v1alpha1_MachineSet_To_wing_MachineSet(in *MachineSet, out *wing.MachineSet, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSet_To_wing_MachineSet(in, out, s)
}

func autoConvert_wing_MachineSet_To_v1alpha1_MachineSet(in *wing.MachineSet, out *MachineSet, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_wing_MachineSetSpec_To_v1alpha1_MachineSetSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_wing_MachineSetStatus_To_v1alpha1_MachineSetStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_wing_MachineSet_To_v1alpha1_MachineSet is an autogenerated conversion function.
func Convert_wing_MachineSet_To_v1alpha1_MachineSet(in *wing.MachineSet, out *MachineSet, s conversion.Scope) error {
	return autoConvert_wing_MachineSet_To_v1alpha1_MachineSet(in, out, s)
}

func autoConvert_v1alpha1_MachineSetList_To_wing_MachineSetList(in *MachineSetList, out *wing.MachineSetList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]wing.MachineSet)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_MachineSetList_To_wing_MachineSetList is an autogenerated conversion function.
func Convert_v1alpha1_MachineSetList_To_wing_MachineSetList(in *MachineSetList, out *wing.MachineSetList, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSetList_To_wing_MachineSetList(in, out, s)
}

func autoConvert_wing_MachineSetList_To_v1alpha1_MachineSetList(in *wing.MachineSetList, out *MachineSetList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]MachineSet)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_wing_MachineSetList_To_v1alpha1_MachineSetList is an autogenerated conversion function.
func Convert_wing_MachineSetList_To_v1alpha1_MachineSetList(in *wing.MachineSetList, out *MachineSetList, s conversion.Scope) error {
	return autoConvert_wing_MachineSetList_To_v1alpha1_MachineSetList(in, out, s)
}

func autoConvert_v1alpha1_MachineSetSpec_To_wing_MachineSetSpec(in *MachineSetSpec, out *wing.MachineSetSpec, s conversion.Scope) error {
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.MinReadySeconds = in.MinReadySeconds
	out.Selector = in.Selector
	if err := Convert_v1alpha1_MachineTemplateSpec_To_wing_MachineTemplateSpec(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_MachineSetSpec_To_wing_MachineSetSpec is an autogenerated conversion function.
func Convert_v1alpha1_MachineSetSpec_To_wing_MachineSetSpec(in *MachineSetSpec, out *wing.MachineSetSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSetSpec_To_wing_MachineSetSpec(in, out, s)
}

func autoConvert_wing_MachineSetSpec_To_v1alpha1_MachineSetSpec(in *wing.MachineSetSpec, out *MachineSetSpec, s conversion.Scope) error {
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.MinReadySeconds = in.MinReadySeconds
	out.Selector = in.Selector
	if err := Convert_wing_MachineTemplateSpec_To_v1alpha1_MachineTemplateSpec(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_wing_MachineSetSpec_To_v1alpha1_MachineSetSpec is an autogenerated conversion function.
func Convert_wing_MachineSetSpec_To_v1alpha1_MachineSetSpec(in *wing.MachineSetSpec, out *MachineSetSpec, s conversion.Scope) error {
	return autoConvert_wing_MachineSetSpec_To_v1alpha1_MachineSetSpec(in, out, s)
}

func autoConvert_v1alpha1_MachineSetSrategy_To_wing_MachineSetSrategy(in *MachineSetSrategy, out *wing.MachineSetSrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_MachineSetSrategy_To_wing_MachineSetSrategy is an autogenerated conversion function.
func Convert_v1alpha1_MachineSetSrategy_To_wing_MachineSetSrategy(in *MachineSetSrategy, out *wing.MachineSetSrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSetSrategy_To_wing_MachineSetSrategy(in, out, s)
}

func autoConvert_wing_MachineSetSrategy_To_v1alpha1_MachineSetSrategy(in *wing.MachineSetSrategy, out *MachineSetSrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_wing_MachineSetSrategy_To_v1alpha1_MachineSetSrategy is an autogenerated conversion function.
func Convert_wing_MachineSetSrategy_To_v1alpha1_MachineSetSrategy(in *wing.MachineSetSrategy, out *MachineSetSrategy, s conversion.Scope) error {
	return autoConvert_wing_MachineSetSrategy_To_v1alpha1_MachineSetSrategy(in, out, s)
}

func autoConvert_v1alpha1_MachineSetSrategyStatusStrategy_To_wing_MachineSetSrategyStatusStrategy(in *MachineSetSrategyStatusStrategy, out *wing.MachineSetSrategyStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_MachineSetSrategyStatusStrategy_To_wing_MachineSetSrategyStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_MachineSetSrategyStatusStrategy_To_wing_MachineSetSrategyStatusStrategy(in *MachineSetSrategyStatusStrategy, out *wing.MachineSetSrategyStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSetSrategyStatusStrategy_To_wing_MachineSetSrategyStatusStrategy(in, out, s)
}

func autoConvert_wing_MachineSetSrategyStatusStrategy_To_v1alpha1_MachineSetSrategyStatusStrategy(in *wing.MachineSetSrategyStatusStrategy, out *MachineSetSrategyStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_wing_MachineSetSrategyStatusStrategy_To_v1alpha1_MachineSetSrategyStatusStrategy is an autogenerated conversion function.
func Convert_wing_MachineSetSrategyStatusStrategy_To_v1alpha1_MachineSetSrategyStatusStrategy(in *wing.MachineSetSrategyStatusStrategy, out *MachineSetSrategyStatusStrategy, s conversion.Scope) error {
	return autoConvert_wing_MachineSetSrategyStatusStrategy_To_v1alpha1_MachineSetSrategyStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_MachineSetStatus_To_wing_MachineSetStatus(in *MachineSetStatus, out *wing.MachineSetStatus, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.FullyLabeledReplicas = in.FullyLabeledReplicas
	out.ReadyReplicas = in.ReadyReplicas
	out.AvailableReplicas = in.AvailableReplicas
	out.ObservedGeneration = in.ObservedGeneration
	out.ErrorReason = common.MachineStatusError(in.ErrorReason)
	out.ErrorMessage = (*string)(unsafe.Pointer(in.ErrorMessage))
	return nil
}

// Convert_v1alpha1_MachineSetStatus_To_wing_MachineSetStatus is an autogenerated conversion function.
func Convert_v1alpha1_MachineSetStatus_To_wing_MachineSetStatus(in *MachineSetStatus, out *wing.MachineSetStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSetStatus_To_wing_MachineSetStatus(in, out, s)
}

func autoConvert_wing_MachineSetStatus_To_v1alpha1_MachineSetStatus(in *wing.MachineSetStatus, out *MachineSetStatus, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.FullyLabeledReplicas = in.FullyLabeledReplicas
	out.ReadyReplicas = in.ReadyReplicas
	out.AvailableReplicas = in.AvailableReplicas
	out.ObservedGeneration = in.ObservedGeneration
	out.ErrorReason = common.MachineStatusError(in.ErrorReason)
	out.ErrorMessage = (*string)(unsafe.Pointer(in.ErrorMessage))
	return nil
}

// Convert_wing_MachineSetStatus_To_v1alpha1_MachineSetStatus is an autogenerated conversion function.
func Convert_wing_MachineSetStatus_To_v1alpha1_MachineSetStatus(in *wing.MachineSetStatus, out *MachineSetStatus, s conversion.Scope) error {
	return autoConvert_wing_MachineSetStatus_To_v1alpha1_MachineSetStatus(in, out, s)
}

func autoConvert_v1alpha1_MachineSpec_To_wing_MachineSpec(in *MachineSpec, out *wing.MachineSpec, s conversion.Scope) error {
	out.Converge = (*wing.MachineSpecManifest)(unsafe.Pointer(in.Converge))
	out.DryRun = (*wing.MachineSpecManifest)(unsafe.Pointer(in.DryRun))
	return nil
}

// Convert_v1alpha1_MachineSpec_To_wing_MachineSpec is an autogenerated conversion function.
func Convert_v1alpha1_MachineSpec_To_wing_MachineSpec(in *MachineSpec, out *wing.MachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSpec_To_wing_MachineSpec(in, out, s)
}

func autoConvert_wing_MachineSpec_To_v1alpha1_MachineSpec(in *wing.MachineSpec, out *MachineSpec, s conversion.Scope) error {
	out.Converge = (*MachineSpecManifest)(unsafe.Pointer(in.Converge))
	out.DryRun = (*MachineSpecManifest)(unsafe.Pointer(in.DryRun))
	return nil
}

// Convert_wing_MachineSpec_To_v1alpha1_MachineSpec is an autogenerated conversion function.
func Convert_wing_MachineSpec_To_v1alpha1_MachineSpec(in *wing.MachineSpec, out *MachineSpec, s conversion.Scope) error {
	return autoConvert_wing_MachineSpec_To_v1alpha1_MachineSpec(in, out, s)
}

func autoConvert_v1alpha1_MachineSpecManifest_To_wing_MachineSpecManifest(in *MachineSpecManifest, out *wing.MachineSpecManifest, s conversion.Scope) error {
	out.Path = in.Path
	out.Hash = in.Hash
	out.RequestTimestamp = in.RequestTimestamp
	return nil
}

// Convert_v1alpha1_MachineSpecManifest_To_wing_MachineSpecManifest is an autogenerated conversion function.
func Convert_v1alpha1_MachineSpecManifest_To_wing_MachineSpecManifest(in *MachineSpecManifest, out *wing.MachineSpecManifest, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSpecManifest_To_wing_MachineSpecManifest(in, out, s)
}

func autoConvert_wing_MachineSpecManifest_To_v1alpha1_MachineSpecManifest(in *wing.MachineSpecManifest, out *MachineSpecManifest, s conversion.Scope) error {
	out.Path = in.Path
	out.Hash = in.Hash
	out.RequestTimestamp = in.RequestTimestamp
	return nil
}

// Convert_wing_MachineSpecManifest_To_v1alpha1_MachineSpecManifest is an autogenerated conversion function.
func Convert_wing_MachineSpecManifest_To_v1alpha1_MachineSpecManifest(in *wing.MachineSpecManifest, out *MachineSpecManifest, s conversion.Scope) error {
	return autoConvert_wing_MachineSpecManifest_To_v1alpha1_MachineSpecManifest(in, out, s)
}

func autoConvert_v1alpha1_MachineStatus_To_wing_MachineStatus(in *MachineStatus, out *wing.MachineStatus, s conversion.Scope) error {
	out.Converge = (*wing.MachineStatusManifest)(unsafe.Pointer(in.Converge))
	out.DryRun = (*wing.MachineStatusManifest)(unsafe.Pointer(in.DryRun))
	return nil
}

// Convert_v1alpha1_MachineStatus_To_wing_MachineStatus is an autogenerated conversion function.
func Convert_v1alpha1_MachineStatus_To_wing_MachineStatus(in *MachineStatus, out *wing.MachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineStatus_To_wing_MachineStatus(in, out, s)
}

func autoConvert_wing_MachineStatus_To_v1alpha1_MachineStatus(in *wing.MachineStatus, out *MachineStatus, s conversion.Scope) error {
	out.Converge = (*MachineStatusManifest)(unsafe.Pointer(in.Converge))
	out.DryRun = (*MachineStatusManifest)(unsafe.Pointer(in.DryRun))
	return nil
}

// Convert_wing_MachineStatus_To_v1alpha1_MachineStatus is an autogenerated conversion function.
func Convert_wing_MachineStatus_To_v1alpha1_MachineStatus(in *wing.MachineStatus, out *MachineStatus, s conversion.Scope) error {
	return autoConvert_wing_MachineStatus_To_v1alpha1_MachineStatus(in, out, s)
}

func autoConvert_v1alpha1_MachineStatusManifest_To_wing_MachineStatusManifest(in *MachineStatusManifest, out *wing.MachineStatusManifest, s conversion.Scope) error {
	out.State = common.MachineManifestState(in.State)
	out.Hash = in.Hash
	out.LastUpdateTimestamp = in.LastUpdateTimestamp
	out.Messages = *(*[]string)(unsafe.Pointer(&in.Messages))
	out.ExitCodes = *(*[]int)(unsafe.Pointer(&in.ExitCodes))
	return nil
}

// Convert_v1alpha1_MachineStatusManifest_To_wing_MachineStatusManifest is an autogenerated conversion function.
func Convert_v1alpha1_MachineStatusManifest_To_wing_MachineStatusManifest(in *MachineStatusManifest, out *wing.MachineStatusManifest, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineStatusManifest_To_wing_MachineStatusManifest(in, out, s)
}

func autoConvert_wing_MachineStatusManifest_To_v1alpha1_MachineStatusManifest(in *wing.MachineStatusManifest, out *MachineStatusManifest, s conversion.Scope) error {
	out.State = common.MachineManifestState(in.State)
	out.Hash = in.Hash
	out.LastUpdateTimestamp = in.LastUpdateTimestamp
	out.Messages = *(*[]string)(unsafe.Pointer(&in.Messages))
	out.ExitCodes = *(*[]int)(unsafe.Pointer(&in.ExitCodes))
	return nil
}

// Convert_wing_MachineStatusManifest_To_v1alpha1_MachineStatusManifest is an autogenerated conversion function.
func Convert_wing_MachineStatusManifest_To_v1alpha1_MachineStatusManifest(in *wing.MachineStatusManifest, out *MachineStatusManifest, s conversion.Scope) error {
	return autoConvert_wing_MachineStatusManifest_To_v1alpha1_MachineStatusManifest(in, out, s)
}

func autoConvert_v1alpha1_MachineStatusStrategy_To_wing_MachineStatusStrategy(in *MachineStatusStrategy, out *wing.MachineStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_MachineStatusStrategy_To_wing_MachineStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_MachineStatusStrategy_To_wing_MachineStatusStrategy(in *MachineStatusStrategy, out *wing.MachineStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineStatusStrategy_To_wing_MachineStatusStrategy(in, out, s)
}

func autoConvert_wing_MachineStatusStrategy_To_v1alpha1_MachineStatusStrategy(in *wing.MachineStatusStrategy, out *MachineStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_wing_MachineStatusStrategy_To_v1alpha1_MachineStatusStrategy is an autogenerated conversion function.
func Convert_wing_MachineStatusStrategy_To_v1alpha1_MachineStatusStrategy(in *wing.MachineStatusStrategy, out *MachineStatusStrategy, s conversion.Scope) error {
	return autoConvert_wing_MachineStatusStrategy_To_v1alpha1_MachineStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_MachineStrategy_To_wing_MachineStrategy(in *MachineStrategy, out *wing.MachineStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_MachineStrategy_To_wing_MachineStrategy is an autogenerated conversion function.
func Convert_v1alpha1_MachineStrategy_To_wing_MachineStrategy(in *MachineStrategy, out *wing.MachineStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineStrategy_To_wing_MachineStrategy(in, out, s)
}

func autoConvert_wing_MachineStrategy_To_v1alpha1_MachineStrategy(in *wing.MachineStrategy, out *MachineStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_wing_MachineStrategy_To_v1alpha1_MachineStrategy is an autogenerated conversion function.
func Convert_wing_MachineStrategy_To_v1alpha1_MachineStrategy(in *wing.MachineStrategy, out *MachineStrategy, s conversion.Scope) error {
	return autoConvert_wing_MachineStrategy_To_v1alpha1_MachineStrategy(in, out, s)
}

func autoConvert_v1alpha1_MachineTemplateSpec_To_wing_MachineTemplateSpec(in *MachineTemplateSpec, out *wing.MachineTemplateSpec, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_MachineSpec_To_wing_MachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_MachineTemplateSpec_To_wing_MachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha1_MachineTemplateSpec_To_wing_MachineTemplateSpec(in *MachineTemplateSpec, out *wing.MachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineTemplateSpec_To_wing_MachineTemplateSpec(in, out, s)
}

func autoConvert_wing_MachineTemplateSpec_To_v1alpha1_MachineTemplateSpec(in *wing.MachineTemplateSpec, out *MachineTemplateSpec, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_wing_MachineSpec_To_v1alpha1_MachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_wing_MachineTemplateSpec_To_v1alpha1_MachineTemplateSpec is an autogenerated conversion function.
func Convert_wing_MachineTemplateSpec_To_v1alpha1_MachineTemplateSpec(in *wing.MachineTemplateSpec, out *MachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_wing_MachineTemplateSpec_To_v1alpha1_MachineTemplateSpec(in, out, s)
}
