// Copyright Jetstack Ltd. See LICENSE for details.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// MachineListerExpansion allows custom methods to be added to
// MachineLister.
type MachineListerExpansion interface{}

// MachineNamespaceListerExpansion allows custom methods to be added to
// MachineNamespaceLister.
type MachineNamespaceListerExpansion interface{}

// MachineSetListerExpansion allows custom methods to be added to
// MachineSetLister.
type MachineSetListerExpansion interface{}

// MachineSetNamespaceListerExpansion allows custom methods to be added to
// MachineSetNamespaceLister.
type MachineSetNamespaceListerExpansion interface{}
